#!/bin/bash

notify(){
  hash notify-send 2>/dev/null && {
    notify-send "$@"
    return
  }
  echo "$@"
}

loc="$(dirname $(realpath ${BASH_SOURCE:-0}))"
[ -f "$loc/colors" ] || touch "$loc/colors"
limit=10

[[ $# -eq 1 && $1 = "-l" ]] && {
  cat "$loc/colors"
  exit
}
[[ $# -eq 1 && $1 = "-j" ]] && {
  text="$(head -n 1 "$loc/colors")"
  allcolors=($(tail -n +2 "$loc/colors"))
  tooltip="<b>   COLORS</b>\n\n"

  tooltip+="-> <b>$text</b>    <span color='$text'></span>\n"
  for i in "${allcolors[@]}"
  do
    tooltip+="   <b>$i</b>    <span color='$i'></span>\n"
  done

  cat << EOF
{ "text":"<span color='$text'></span>", "tooltip":"$tooltip"}  
EOF

  exit
}

hash hyprpicker 2>/dev/null || {
  notify "hyprpicker is not installed"
  exit
}
killall -q hyprpicker
color=$(hyprpicker)
prevColors=$(head -n $((limit-1)) "$loc/colors")
echo "$color" > "$loc/colors"
echo "$prevColors" >> "$loc/colors"
pkill  -RTMIN+10 waybar
