#!/bin/python3

"""
This script will move tiling window and non tiling one with same key press
Uses hyprctl.
"""

import json
import subprocess
import sys

dir = sys.argv[1]


def getVal(dir):
    val = 50
    if dir == "r":
        return f"{val} 0"
    if dir == "d":
        return f"0 {val}"
    if dir == "l":
        return f"-{val} 0"
    if dir == "u":
        return f"0 -{val}"


command = subprocess.run(
    "hyprctl activewindow -j", shell=True, capture_output=True, check=True, text=True
)

data = json.loads(command.stdout)

if data["floating"]:
    val = getVal(dir)
    subprocess.run(
        f"hyprctl dispatcher moveactive {val}",
        shell=True,
        capture_output=True,
        check=True,
        text=True,
    )
else:
    subprocess.run(
        f"hyprctl dispatcher movewindow {dir}",
        shell=True,
        capture_output=True,
        check=True,
        text=True,
    )
