#!/bin/bash

check(){
  command -v $1 1>/dev/null
}

check swayidle || exit 0
check swaylock || exit 0

# check sway-audio-idle-inhibit && {
#   killall -q sway-audio-idle-inhibit
#   exec sway-audio-idle-inhibit &>/dev/null &
# }

killall -q swayidle
killall -q swaylock

LOCK_TIME=${LOCK_TIME:-150}
SCRN_TIME=$((LOCK_TIME + 50))
SUSPEND_TIME=${SUSPEND_TIME:-150}
SUSPEND_TIME=$((SUSPEND_TIME + SCRN_TIME))

lock="swaylock -f"
unlock="killall -q swaylock"
suspend="systemctl suspend"

[ -f "$HOME/bin/lock" ] && lock="$HOME/bin/lock"

swayidle -w \
before-sleep "$lock" \
lock "$lock" \
unlock "$unlock" \
timeout "$LOCK_TIME" "loginctl lock-session" \
timeout "$SCRN_TIME" "sleep 1 && hyprctl dispatch dpms off" resume "sleep 1 && hyprctl dispatch dpms on" \
timeout "$SUSPEND_TIME" "$suspend" &>/dev/null &

