#!/usr/bin/env bash

check() {
	command -v "$1" &>/dev/null
}

notify() {
	check notify-send && notify-send "$@" || echo "$@"
}

check socat || {
	notify "socat not available"
}

handle() {
	echo "$line"

	if [[ ${1:0:12} == "monitoradded" ]]; then
		"$HOME/.config/hypr/scripts/monitor"
	fi
  if [[ ${1:0:14} == "monitorremoved" ]]; then
		"$HOME/.config/hypr/scripts/monitor"
	fi
}

socat - UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock | while read -r line; do handle "$line"; done
