#!/bin/bash

# This will set the border colors according to wall

hyprctl keyword general:col.inactive_border 0x00000000

foreground='#ff0000'
cursor='#ff0000'
[ -f "$HOME/.config/wpg/templates/colors.sh" ] && . "$HOME/.config/wpg/templates/colors.sh"

acolor=$(echo $active | sed 's/#//g')
ccolor=$(echo $cursor | sed 's/#//g')
hyprctl keyword general:col.active_border "0xff$acolor"
hyprctl keyword dwindle:col.group_border_active "0xff$ccolor"
hyprctl keyword dwindle:col.group_border "0x11$ccolor"
