#!/usr/bin/env bash

check() {
	command -v "$1" 1>/dev/null
}
rootmgr="sudo"
check doas && rootmgr="doas"

# There are three states in this (savermode, default, performance)
# savermode: make auto-cpufreq on powersave (cpugoverner), hyprland config to reduce battery consumtion (optional)
#   TODO: addition of Core Ctrl battery management

savermode() {
	[[ "$(auto-cpufreq --get-state)" = *"powersave"* ]] && {
		check hyprctl || return
		hyprctl --batch "\
      keyword animations:enabled 0;\
      keyword decoration:drop_shadow 0;\
      keyword decoration:blur 0;\
      keyword general:gaps_in 0;\
      keyword general:gaps_out 0;\
      keyword general:border_size 1;\
      keyword decoration:rounding 0"
	}
	check auto-cpufreq && {
		$rootmgr auto-cpufreq --force="powersave" &>/dev/null
	}
}

default() {

	check auto-cpufreq && {
		$rootmgr auto-cpufreq --force="reset" &>/dev/null
	}
	check hyprctl || return
	hyprctl reload
}

performance() {
	check auto-cpufreq && {
		$rootmgr auto-cpufreq --force="performance" &>/dev/null
	}
	check hyprctl || return
	hyprctl reload
}

getdata() {
	text="<b></b>"
	tooltip=""
	state=""
	check hyprctl && {
		glory=$(hyprctl getoption animations:enabled | awk 'NR==2{print $2}')
		tooltip+="<b>Hyprland:\n</b>"
		[ "$glory" -eq 1 ] && glory="enabled" || glory="disabled"
		tooltip+="Glory Stuff: $glory\n"
	}
	check auto-cpufreq && {
		state="$(auto-cpufreq --get-state)"
		tooltip+="<b>Auto Cpufreq:\n</b>auto-cpufreq: $state"
	}
	class="$state"
	cat <<EOF
  { "text": "$text", "tooltip" : "$tooltip", "class" : "$class" }
EOF
}

[[ "$1" = *"save"* ]] && {
	savermode
	pkill -SIGRTMIN+5 waybar
}
[[ "$1" = *"default"* ]] && {
	default
	pkill -SIGRTMIN+5 waybar
}
[[ "$1" = *"performance"* ]] && {
	performance
	pkill -SIGRTMIN+5 waybar
}
[[ "$1" = *"getdata"* ]] && {
	getdata
}
