#!/usr/bin/env bash

check(){
  command -v $1 1>/dev/null
}

check cliphist && {
  (( $(cliphist list | wc -l) > 100 )) && {
    [ -f "$HOME/.cache/cliphist/db" ] && rm ~/.cache/cliphist/db
  }
}

hyprctl setcursor "GoogleDot-Black" 24 
gnome-settings(){
  cmd="gsettings set org.gnome.desktop.interface"
  theme="FlatColor"
  [ -d "$HOME/.themes/oomox-gtk-nik-theme" ] && theme="oomox-gtk-nik-theme"
  $cmd gtk-theme "$theme"
  $cmd icon-theme 'la-capitaine'
  $cmd cursor-theme 'GoogleDot-Black'
  $cmd font-name 'Comic Code Ligatures Nerd Font'
}
gnome-settings

