# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#c7c1cd"          # Main text color
theme[title]="#c7c1cd"            # Title color for boxes
theme[hi_fg]="#5B7291"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#8b878f"       # Color of inactive/disabled text
theme[graph_text]="#6C8FAE"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#0f131b"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#454e61"       # Background color of selected item in processes box
theme[selected_fg]="#c7c1cd"       # Foreground color of selected item in processes box
theme[proc_misc]="#6C8FAE"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#5B7291"           # Cpu box outline color
theme[mem_box]="#57627A"           # Memory/disks box outline color
theme[net_box]="#5B7291"           # Net up/down box outline color
theme[proc_box]="#57627A"          # Processes box outline color
theme[div_line]="#57627A"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#8b878f"          # Background color of the percentage meters
theme[used_start]="#6C8FAE"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#6C8FAE"
theme[available_start]="#7CACC3"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#7CACC3"
theme[cached_start]="#6C8FAE"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#6C8FAE"
theme[free_start]="#7CACC3"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#7CACC3"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#5B7291"        # CPU graph colors
theme[cpu_mid]="#9E6575"
theme[cpu_end]="#57627A"
theme[download_start]="#6C8FAE"    # Download graph colors
theme[download_mid]="#57627A"
theme[download_end]="#57627A"  
theme[upload_start]="#9E6575"     # Upload graph colors
theme[upload_mid]="#9E6575"
theme[upload_end]="#7CACC3"
theme[process_start]="#6C8FAE"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#7CACC3"
theme[process_end]="#977891"
