# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#b9cac2"          # Main text color
theme[title]="#b9cac2"            # Title color for boxes
theme[hi_fg]="#3D8186"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#818d87"       # Color of inactive/disabled text
theme[graph_text]="#719A91"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#122225"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#736f64"       # Background color of selected item in processes box
theme[selected_fg]="#b9cac2"       # Foreground color of selected item in processes box
theme[proc_misc]="#719A91"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#3D8186"           # Cpu box outline color
theme[mem_box]="#918B7D"           # Memory/disks box outline color
theme[net_box]="#3D8186"           # Net up/down box outline color
theme[proc_box]="#918B7D"          # Processes box outline color
theme[div_line]="#918B7D"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#818d87"          # Background color of the percentage meters
theme[used_start]="#719A91"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#719A91"
theme[available_start]="#8D958B"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#8D958B"
theme[cached_start]="#719A91"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#719A91"
theme[free_start]="#8D958B"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#8D958B"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#3D8186"        # CPU graph colors
theme[cpu_mid]="#317B82"
theme[cpu_end]="#918B7D"
theme[download_start]="#719A91"    # Download graph colors
theme[download_mid]="#918B7D"
theme[download_end]="#918B7D"  
theme[upload_start]="#317B82"     # Upload graph colors
theme[upload_mid]="#317B82"
theme[upload_end]="#8D958B"
theme[process_start]="#719A91"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#8D958B"
theme[process_end]="#478688"
