# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#7ab4d7"          # Main text color
theme[title]="#7ab4d7"            # Title color for boxes
theme[hi_fg]="#668C2C"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#557d96"       # Color of inactive/disabled text
theme[graph_text]="#AABA60"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#030D0B"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#3c5748"       # Background color of selected item in processes box
theme[selected_fg]="#7ab4d7"       # Foreground color of selected item in processes box
theme[proc_misc]="#AABA60"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#668C2C"           # Cpu box outline color
theme[mem_box]="#215160"           # Memory/disks box outline color
theme[net_box]="#668C2C"           # Net up/down box outline color
theme[proc_box]="#215160"          # Processes box outline color
theme[div_line]="#215160"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#557d96"          # Background color of the percentage meters
theme[used_start]="#AABA60"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#AABA60"
theme[available_start]="#186496"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#186496"
theme[cached_start]="#AABA60"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#AABA60"
theme[free_start]="#186496"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#186496"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#668C2C"        # CPU graph colors
theme[cpu_mid]="#4C6E5B"
theme[cpu_end]="#215160"
theme[download_start]="#AABA60"    # Download graph colors
theme[download_mid]="#215160"
theme[download_end]="#215160"  
theme[upload_start]="#4C6E5B"     # Upload graph colors
theme[upload_mid]="#4C6E5B"
theme[upload_end]="#186496"
theme[process_start]="#AABA60"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#186496"
theme[process_end]="#628F5D"
