# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#95d1dd"          # Main text color
theme[title]="#95d1dd"            # Title color for boxes
theme[hi_fg]="#C8B569"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#68929a"       # Color of inactive/disabled text
theme[graph_text]="#9C7292"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#0d0d12"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#465173"       # Background color of selected item in processes box
theme[selected_fg]="#95d1dd"       # Foreground color of selected item in processes box
theme[proc_misc]="#9C7292"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#C8B569"           # Cpu box outline color
theme[mem_box]="#A05F67"           # Memory/disks box outline color
theme[net_box]="#C8B569"           # Net up/down box outline color
theme[proc_box]="#A05F67"          # Processes box outline color
theme[div_line]="#A05F67"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#68929a"          # Background color of the percentage meters
theme[used_start]="#9C7292"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#9C7292"
theme[available_start]="#F5768E"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#F5768E"
theme[cached_start]="#9C7292"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#9C7292"
theme[free_start]="#F5768E"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#F5768E"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#C8B569"        # CPU graph colors
theme[cpu_mid]="#688E61"
theme[cpu_end]="#A05F67"
theme[download_start]="#9C7292"    # Download graph colors
theme[download_mid]="#A05F67"
theme[download_end]="#A05F67"  
theme[upload_start]="#688E61"     # Upload graph colors
theme[upload_mid]="#688E61"
theme[upload_end]="#F5768E"
theme[process_start]="#9C7292"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#F5768E"
theme[process_end]="#586690"
