# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#cbc7e1"          # Main text color
theme[title]="#cbc7e1"            # Title color for boxes
theme[hi_fg]="#B47688"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#8e8b9d"       # Color of inactive/disabled text
theme[graph_text]="#6F92DB"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#0d0d12"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#2a8aa0"       # Background color of selected item in processes box
theme[selected_fg]="#cbc7e1"       # Foreground color of selected item in processes box
theme[proc_misc]="#6F92DB"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#B47688"           # Cpu box outline color
theme[mem_box]="#317A97"           # Memory/disks box outline color
theme[net_box]="#B47688"           # Net up/down box outline color
theme[proc_box]="#317A97"          # Processes box outline color
theme[div_line]="#317A97"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#8e8b9d"          # Background color of the percentage meters
theme[used_start]="#6F92DB"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#6F92DB"
theme[available_start]="#7AA2F7"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#7AA2F7"
theme[cached_start]="#6F92DB"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#6F92DB"
theme[free_start]="#7AA2F7"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#7AA2F7"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#B47688"        # CPU graph colors
theme[cpu_mid]="#576D9F"
theme[cpu_end]="#317A97"
theme[download_start]="#6F92DB"    # Download graph colors
theme[download_mid]="#317A97"
theme[download_end]="#317A97"  
theme[upload_start]="#576D9F"     # Upload graph colors
theme[upload_mid]="#576D9F"
theme[upload_end]="#7AA2F7"
theme[process_start]="#6F92DB"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#7AA2F7"
theme[process_end]="#35ADC9"
