#!/usr/bin/env bash

echo ">>>>>>No checks are placed!!<<<<<<<<"
echo ""

myloc="$(dirname $(realpath ${BASH_SOURCE[@]:-0}))"

linking() {
	echo "$1 -> $2"
	ln -sf "$1" "$2"
	echo ""
}

# linking "$myloc/hypr" "$HOME/.config/"
linking "$myloc/waybar" "$HOME/.config/"
linking "$myloc/wpg" "$HOME/.config/"
linking "$myloc/foot" "$HOME/.config/"
linking "$myloc/mako" "$HOME/.config/"
linking "$myloc/zathura" "$HOME/.config/"
linking "$myloc/btop" "$HOME/.config/"
linking "$myloc/wlogout" "$HOME/.config/"
linking "$myloc/rofi" "$HOME/.config/"
linking "$myloc/yay" "$HOME/.config/"
linking "$myloc/neofetch" "$HOME/.config/"
linking "$myloc/MangoHud" "$HOME/.config/"
linking "$myloc/udiskie" "$HOME/.config/"
linking "$myloc/qt5ct" "$HOME/.config/"
linking "$myloc/qt6ct" "$HOME/.config/"
linking "$myloc/alacritty" "$HOME/.config/"
linking "$myloc/gtk-4.0" "$HOME/.config/"
linking "$myloc/networkmanager-dmenu" "$HOME/.config/"
mkdir -p Mailspring/packages
linking "$myloc/minimal-dark" "$HOME/.config/Mailspring/packages/"
# linking "$myloc/urlview" "$HOME/.urlview"

mkdir -p "$HOME/.themes/"
[ -d "$HOME/.themes/FlatColor" ] && rm -rf "$HOME/.themes/FlatColor"
linking "$myloc/FlatColor" "$HOME/.themes/"

linking "$myloc/bin" "$HOME/"
