#!/usr/bin/env bash

check() {
	command -v "$1" 1>/dev/null
}

check sensors || exit

data="$(sensors coretemp-isa-0000 | sed 's/+//g')"
package="$(echo "$data" | awk -e '/Package/ {print $4}')"
coretemp="$(echo "$data" | awk -e '/Core/ {print $3}')"

tooltip="<b>Core Temp: $package </b>\n"

# "format-icons" : [ "", "", "", "", "" ] ,
tempint=${package%.*}
icon="<span color='#7AA2F7'>$package </span>"
[ "$tempint" -gt 60 ] && icon="<span color='#00ffff'>$package </span>"
[ "$tempint" -gt 70 ] && icon="<span color='#A6DA95'>$package </span>"
[ "$tempint" -gt 85 ] && icon="<span color='#FAB387'>$package </span>"
[ "$tempint" -gt 95 ] && icon="<span color='#ff0000'>$package </span>"

j=0
for i in $coretemp; do
	tooltip+="Core $j: $i\n"
	((j = j + 1))
done
cat <<EOF
{"text":"$icon","tooltip":"$tooltip",}
EOF
