#!/usr/bin/env bash

check(){
  command -v "$1" 1>/dev/null
}

notify(){
  check notify-send && {
    notify-send "$@"
    return
  }
  echo "$@"
}

check checkupdates-with-aur || {
  cat << EOF
  {"text":"ERR","tooltip":"checkupdates-with-aur is not installed"}
EOF
  exit 1
}
IFS=$'\n'$'\r'

killall -q checkupdates-with-aur
mapfile -t updates < <(checkupdates-with-aur)

text=${#updates[@]}
tooltip="<b>$text  updates (arch+aur) </b>\n"

[ "$text" -eq 0 ] && text="" || text+="  "

for i in "${updates[@]}"
do
  tooltip+="$i\n"
done

cat << EOF
{ "text":"$text", "tooltip":"$tooltip"}  
EOF
